function Build-PSBuildUpdatableHelp {
    <#
    .SYNOPSIS
        Create updatable help .cab file based on PlatyPS markdown help.
    .DESCRIPTION
        Create updatable help .cab file based on PlatyPS markdown help.

        Requires the module manifest to declare a HelpInfoUri. That URI is where Update-Help
        looks for the help content, so a cabinet built without one cannot be consumed.
    .PARAMETER DocsPath
        Path to PlatyPS markdown help files. Must contain a locale directory holding the
        module landing page, <locale>/<Module>.md.
    .PARAMETER OutputPath
        Path to create updatable help .cab file in.
    .PARAMETER ModulePath
        Path to the built module. The MAML written by Build-PSBuildMAMLHelp is read from
        <ModulePath>/<locale>, and the manifest is read from <ModulePath>/<Module>.psd1.
    .PARAMETER Module
        Name of the module to create a .cab file for.
    .EXAMPLE
        PS> Build-PSBuildUpdatableHelp -DocsPath ./docs -OutputPath ./Output/UpdatableHelp -ModulePath ./Output/MyModule/1.0.0 -Module MyModule

        Create help .cab file based on PlatyPS markdown help.
    #>
    [CmdletBinding()]
    param(
        [parameter(Mandatory)]
        [string]$DocsPath,

        [parameter(Mandatory)]
        [string]$OutputPath,

        [parameter(Mandatory)]
        [string]$ModulePath,

        [parameter(Mandatory)]
        [string]$Module
    )

    if ($null -ne $IsWindows -and -not $IsWindows) {
        Write-Warning $LocalizedData.MakeCabNotAvailable
        return
    }

    # Update-Help resolves help content through the manifest's HelpInfoUri. Without one,
    # New-HelpCabinetFile still writes the cabinet and its zip but fails before writing the
    # HelpInfo.xml that makes them findable, leaving output that looks complete and is not.
    # Refusing up front is better than producing that.
    $manifestPath = [IO.Path]::Combine($ModulePath, "$Module.psd1")
    if (-not (Test-Path -LiteralPath $manifestPath)) {
        Write-Warning ($LocalizedData.UnableToFindModuleManifest -f $manifestPath)
        return
    }
    $helpInfoUri = (Import-PowerShellDataFile -Path $manifestPath).HelpInfoUri
    if ([string]::IsNullOrWhiteSpace($helpInfoUri)) {
        Write-Warning ($LocalizedData.HelpInfoUriRequired -f $Module)
        return
    }

    # Work out what can actually be built before touching OutputPath. Clearing it first and
    # then skipping every locale would delete a previous build's cabinet and replace it with
    # nothing, which is the same half-produced outcome the guards above exist to prevent.
    # Only the locale directories, not every subdirectory of the docs tree. A project keeps
    # more than generated help under docs -- images, guides, an api folder -- and reporting a
    # missing landing page for each of them is noise about directories that were never help
    # in the first place. See psake/PowerShellBuild#124.
    $helpLocale = @(Get-PSBuildHelpLocale -Path $DocsPath -ModulePath $ModulePath)

    $cabinetWork = foreach ($locale in $helpLocale) {
        # The landing page is a module document rather than command help. It is what carries
        # the module GUID and locale into the cabinet, and it is generated by
        # Build-PSBuildMarkdown; a docs tree from an older build will not have one.
        $markdownModuleFile = [IO.Path]::Combine($DocsPath, $locale, "$Module.md")
        if (-not (Test-Path -LiteralPath $markdownModuleFile)) {
            Write-Warning ($LocalizedData.ModuleLandingPageNotFound -f $markdownModuleFile, $locale)
            continue
        }

        $cabinetFilesFolder = [IO.Path]::Combine($ModulePath, $locale)
        if (-not (Test-Path -LiteralPath $cabinetFilesFolder)) {
            Write-Warning ($LocalizedData.FolderDoesNotExist -f $cabinetFilesFolder)
            continue
        }

        [PSCustomObject]@{
            CabinetFilesFolder = $cabinetFilesFolder
            MarkdownModuleFile = $markdownModuleFile
        }
    }

    if (-not $cabinetWork) {
        return
    }

    # Create updatable help output directory
    if (-not (Test-Path -LiteralPath $OutputPath)) {
        $newItemSplat = @{
            ItemType = 'Directory'
            Verbose  = ($VerbosePreference -eq 'Continue')
            Path     = $OutputPath
        }
        New-Item @newItemSplat > $null
    } else {
        Write-Verbose ($LocalizedData.DirectoryAlreadyExists -f $OutputPath)
        $removeItemSplat = @{
            Recurse = $true
            Force   = $true
            Verbose = ($VerbosePreference -eq 'Continue')
        }
        Get-ChildItem $OutputPath | Remove-Item @removeItemSplat
    }

    foreach ($work in $cabinetWork) {
        $cabinetParameters = @{
            CabinetFilesFolder = $work.CabinetFilesFolder
            MarkdownModuleFile = $work.MarkdownModuleFile
            OutputFolder       = $OutputPath
            Verbose            = ($VerbosePreference -eq 'Continue')
        }
        New-HelpCabinetFile @cabinetParameters > $null
    }
}
