name: Test
on:
  push:
    branches: [ $default-branch ]
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Test
      shell: pwsh
      env:
        DEBUG: ${{ runner.debug == '1' }}
      run: |
        if($env:DEBUG -eq 'true' -or $env:DEBUG -eq '1') {
          $DebugPreference = 'Continue'
        }
        ./build.ps1 -Task Test -Bootstrap
