name: Test
on:
  push:
    branches: [ $default-branch ]
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Test
      shell: pwsh
      run: ./build.ps1 -Task Test -Bootstrap
